
language: objective-c
osx_image: xcode11

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -project ObjCRetriableOperation.xcodeproj -target 'ObjCRetriableOperation iOS' -sdk iphoneos -configuration Release | xcpretty
    - xcodebuild clean build -project ObjCRetriableOperation.xcodeproj -target 'ObjCRetriableOperation macOS' -sdk macosx -configuration Release | xcpretty
    - xcodebuild clean build -project ObjCRetriableOperation.xcodeproj -target 'ObjCRetriableOperation watchOS' -sdk watchos -configuration Release | xcpretty
    - xcodebuild clean build -project ObjCRetriableOperation.xcodeproj -target 'ObjCRetriableOperation tvOS' -sdk appletvos -configuration Release | xcpretty